// import { InMemoryDbService } from "angular-in-memory-web-api";
// import { container } from "../_models/container";

// export class MockContainerService implements InMemoryDbService {
//   createDb() {
//     const container_detail: Array<container> = [
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "40",
//         ContainerTypeCode: "DNV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/1.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "40",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/2.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "40",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "London",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/3.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "40",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/5.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 2521,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "40",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/6.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "40",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/7.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "40",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/1.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "40",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/2.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "40",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/3.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "40",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/5.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "40",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/6.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "40",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/7.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "40",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 500,
//         Image: "assets/images/1.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "40",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/2.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "40",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Felixstowe",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/3.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "40",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/5.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 23,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "40",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 500,
//         Image: "assets/images/6.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "40",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/7.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "40",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/1.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "40",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/2.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "40",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/3.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "40",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/5.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "40",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/6.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "40",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/7.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "40",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/1.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "40",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 500,
//         Image: "assets/images/2.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "40",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "London",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/3.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "40",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/5.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 23,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "40",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/6.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "40",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/7.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "40",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/1.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "40",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/2.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "40",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/3.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "40",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 500,
//         Image: "assets/images/5.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "40",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/6.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "40",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/7.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "40",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/1.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "40",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/2.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Felixstowe",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/3.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/5.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 2521,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/6.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 500,
//         Image: "assets/images/7.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/1.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DNV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/2.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DNV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/3.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DNV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/5.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DNV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/6.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DNV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 500,
//         Image: "assets/images/7.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DNV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/1.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/2.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "London",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/3.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/5.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 2521,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/6.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/7.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "St Louis",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/1.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/2.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/3.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/5.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/6.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/7.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "HC",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/1.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DNV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/2.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DNV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Felixstowe",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/3.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DNV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 12600,
//         Image: "assets/images/5.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 2521,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DNV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/6.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DNV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/7.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DNV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/1.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DNV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/2.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DNV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/3.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DNV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/5.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DNV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/6.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DNV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/7.jpg"
//       }, {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DNV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/1.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DNV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/2.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DNV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "London",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/3.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DNV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/5.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 2521,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DNV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/6.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DNV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/7.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DNV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "Cape Town (DCP)",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/1.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DNV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/2.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DNV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/3.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DNV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/5.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 25,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DNV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/6.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 24,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DNV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/7.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 33,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/1.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 35,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/2.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 39,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "London",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/3.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 80,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/5.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 121,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/6.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 24,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/7.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 24,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/1.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 24,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/2.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 24,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/3.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 24,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/5.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 24,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/6.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 24,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/7.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 24,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/1.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 24,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/2.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 24,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DNV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "London",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/3.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 24,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DNV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/5.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 121,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DNV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/6.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 24,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DNV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/7.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 24,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DNV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/1.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 24,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DNV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/2.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 24,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DNV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/3.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 24,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DNV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/5.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 24,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DNV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "USED",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/6.jpg"
//       },
//       {
//         AvailableUnits: 1,
//         DepotId: 361,
//         ContainerSizeId: 1,
//         ContainerTypeId: 1,
//         SaleCondtionId: 1,
//         ColorCodeId: 24,
//         CountryId: 260,
//         CityId: 2243,
//         DepotCode: "2ADELIDE",
//         ContainerSizeCode: "20",
//         ContainerTypeCode: "DNV",
//         CurrencyId: 2,
//         VaildFrom: "11-JUN-2017",
//         ValidTo: "11-JUN-2018",
//         CityName: "Adelaide",
//         SaleConditionName: "NEW",
//         ColorCodeName: "RAL 1001 TAN",
//         DepotName: "AADDE",
//         ExpectedUnits: 50,
//         SalePrice: 2600,
//         Image: "assets/images/7.jpg"
//       }
//     ];
//     const item_data = [
//       {
//         username: "SOFP20180025",
//         custumername: "40/HC",
//         country: "RAL 1000 TAN LIGHT BLUE",
//         status: "COPACS",
//         phoneno: 1234567890,
//         email: "tellus.eu.augue@arcu.com",
//         saleinvoice: "MUL1258633",
//         salerelease: "SaleInvoice20180220121634772",
//         invc_fle_pth:"SaleInvoice20180206150127748"
//       },
//       {
//         username: "SOFP20180026",
//         custumername: "40/HC",
//         country: "RAL 1000 TAN LIGHT BLUE",
//         status: "COPACS",
//         phoneno: 1234567890,
//         email: "tellus.eu.augue@arcu.com",
//         saleinvoice: "MUL1258633",
//         salerelease: "SaleInvoice20180220121634772",
//         invc_fle_pth:"SaleInvoice20180220121637318"
//       },
//       {
//         username: "SOFP20180027",
//         custumername: "40/HC",
//         country: "RAL 1000 TAN LIGHT BLUE",
//         status: "COPACS",
//         phoneno: 1234567890,
//         email: "tellus.eu.augue@arcu.com",
//         saleinvoice: "MUL1258633",
//         salerelease: "SaleInvoice20180220121634772",
//         invc_fle_pth:"SaleInvoice20180220121639728"
//       },
//       {
//         username: "SOFP20180028",
//         custumername: "40/HC",
//         country: "RAL 1000 TAN LIGHT BLUE",
//         status: "COPACS",
//         phoneno: 1234567890,
//         email: "tellus.eu.augue@arcu.com",
//         saleinvoice: "MUL1258633",
//         salerelease: "SaleInvoice20180220121634772",
//         invc_fle_pth:"SaleInvoice20180220121634772"
        
//       },
//       {
//         username: "Wing",
//         custumername: "40/HC",
//         country: "RAL 1000 TAN LIGHT BLUE",
//         status: "COPACS",
//         phoneno: 1234567890,
//         email: "tellus.eu.augue@arcu.com",
//         saleinvoice: "MUL1258633",
//         salerelease: "SaleInvoice20180220121634772",
//         invc_fle_pth:"SaleInvoice20180220121634772"
//       },
//       {
//         username: "Wing",
//         custumername: "40/HC",
//         country: "COPACS",  
//         status: "Deactivated",
//         phoneno: 1234567890,
//         email: "tellus.eu.augue@arcu.com",
//         saleinvoice: "MUL1258633",
//         salerelease: "SaleInvoice20180220121634772",
//         invc_fle_pth:"SaleInvoice20180220121634772"
//       },
//       {
//         username: "Wing",
//         custumername: "Dell",
//         country: "hungary",
//         status: "pending",
//         phoneno: 1234567890,
//         email: "tellus.eu.augue@arcu.com",
//         saleinvoice: "SaleInvoice20180220121639728",
//         salerelease: "SaleInvoice20180220121634772",
//         invc_fle_pth:"SaleInvoice20180220121634772"
//       },
//       {
//         username: "Wing12",
//         custumername: "Dell",
//         country: "hungary",
//         status: "pending",
//         phoneno: 1234567890,
//         email: "tellus.eu.augue@arcu.com",
//         saleinvoice: "SaleInvoice20180220121639728",
//         salerelease: "SaleInvoice20180220121634772",
//         invc_fle_pth:"SaleInvoice20180220121634772"
//       }
//     ];
//     return { container_detail, item_data };
//   }
// }
